# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 14:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words_lists', '0001_initial'),
        ('drawings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginning', models.DateTimeField(auto_now_add=True, verbose_name='Beginning of the draw')),
                ('end', models.DateTimeField(blank=True, default=None, null=True, verbose_name='End of the draw')),
                ('skipped', models.BooleanField(default=False)),
                ('skipped_because_AFK', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DrawingGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('END_ON_SCORE', 'The game ends when a score is achieved by a player'), ('END_ON_TOUR', 'The game ends after a certain amount of tours'), ('END_ON_TIME', 'The game ends after a certain amount of time')], default='END_ON_SCORE', max_length=16)),
                ('tour_duration', models.IntegerField(default=4, verbose_name='Duration per tour, in minutes')),
                ('beginning', models.DateTimeField(auto_now_add=True, verbose_name='Beginning of the draw')),
                ('end', models.DateTimeField(blank=True, default=None, null=True, verbose_name='End of the draw')),
                ('current_draw', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drawings.Draw')),
            ],
        ),
        migrations.RemoveField(
            model_name='wordslist',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='wordslist',
            name='words',
        ),
        migrations.RemoveField(
            model_name='drawer',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='drawingroom',
            name='drawers',
        ),
        migrations.AddField(
            model_name='drawer',
            name='order',
            field=models.IntegerField(default=0, verbose_name="The drawer's order in the game"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drawer',
            name='score',
            field=models.IntegerField(default=0, verbose_name="The drawer's score in the game"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drawer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drawer',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='drawingroom',
            name='game_type',
            field=models.CharField(choices=[('END_ON_SCORE', 'The game ends when a score is achieved by a player'), ('END_ON_TOUR', 'The game ends after a certain amount of tours'), ('END_ON_TIME', 'The game ends after a certain amount of time')], default='END_ON_SCORE', max_length=16),
        ),
        migrations.AddField(
            model_name='drawingroom',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='drawingroom',
            name='state',
            field=models.CharField(choices=[('IDLE', 'Waiting to play'), ('IN_GAME', 'In game'), ('DEAD', 'Dead')], default='IDLE', max_length=8),
        ),
        migrations.AddField(
            model_name='drawingroom',
            name='tour_duration',
            field=models.IntegerField(default=4, verbose_name='Duration per tour, in minutes'),
        ),
        migrations.AddField(
            model_name='drawingroom',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drawingroom',
            name='words_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='words_lists.WordsList'),
        ),
        migrations.DeleteModel(
            name='Word',
        ),
        migrations.DeleteModel(
            name='WordsList',
        ),
        migrations.AddField(
            model_name='drawinggame',
            name='drawers',
            field=models.ManyToManyField(related_name='games', to='drawings.Drawer'),
        ),
        migrations.AddField(
            model_name='drawinggame',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drawings.DrawingRoom'),
        ),
        migrations.AddField(
            model_name='drawinggame',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='games_won', to='drawings.Drawer'),
        ),
        migrations.AddField(
            model_name='drawinggame',
            name='words_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='words_lists.WordsList'),
        ),
        migrations.AddField(
            model_name='draw',
            name='drawer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draws', to='drawings.Drawer'),
        ),
        migrations.AddField(
            model_name='draw',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draws_history', to='drawings.DrawingGame'),
        ),
        migrations.AddField(
            model_name='draw',
            name='guessed_by',
            field=models.ManyToManyField(related_name='guesses', to='drawings.Drawer', verbose_name='Word guessed by...'),
        ),
        migrations.AddField(
            model_name='draw',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draws', to='words_lists.Word'),
        ),
        migrations.AddField(
            model_name='drawingroom',
            name='active_game',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='drawings.DrawingGame'),
        ),
    ]
